### PR TITLE
[POAE7-792] revert streamAPI based PMem spill

### PR DESCRIPTION
**Pull request by yma11**
## What changes were proposed in this pull request?

revert previous streamAPI based PMem Spill

## How was this patch tested?

Not tested

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by yma11** [comment]
@winningsix Please help merge this PR so that I will commit new PMEM spill options.

**Comment by winningsix** [comment]
Bear me please. Can you explain me a little further why we need to revert stream API work? 

BTW, please file a sub-ticket under POAE7-792.

**Comment by yma11** [comment]
They are different designs and not easy to coexist as they have conflicted modifications on BytesToBytesMap and UnsafeExternalSorter. If we want to keep all these options, I suggest to use different branches instead keeping them in a single branch with chaos.

**Comment by yma11** [comment]
based on offline discussion, I will port this feature with framework together. No need to revert so close it.

**Pull request closed without merging**
