### PR TITLE
Support one pmem path on AppDirect mode of RDD Cache

### PR DESCRIPTION
**Pull request by JustDoCoder**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. unit tests, integration tests, manual tests)

(If this patch involves UI changes, please attach a screenshot; otherwise, remove this)

### CODE REVIEW

**Comment by yeyuqiang** [comment]
LGTM

**Comment by winningsix** [comment]
Currently assumption is Spark is NUMA binding. So it means 2 NUMA nodes. 
```
val pmemInitialPaths = conf.get("spark.memory.pmem.initial.path", "").split(",")
```
If the assumption is only one path, we will introduce an empty path. 
```
val path = pmemInitialPaths(numaNodeId % 2)
```

**Comment by JustDoCoder** [comment]
Thank you for your guidance. This may cause the creation of the initialization path to fail. @winningsix

**Comment by winningsix** [comment]
@JustDoCoder Can you help add some unite tests in your next fix? That will be very helpful! Thanks!

**Comment by JustDoCoder** [comment]
@winningsix It's my pleasure to do

**Pull request merged**
